/* DO NOT EDIT THIS FILE - it is machine generated */
#include "Platform.h"
/* Header for class org_swdc_pdfium_internal_PDFPageObjectImpl */

#ifndef _Included_org_swdc_pdfium_internal_PDFPageObjectImpl
#define _Included_org_swdc_pdfium_internal_PDFPageObjectImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    getObjectCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_getObjectCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    getPageObject
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_getPageObject
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    getPageObjectType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_getPageObjectType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    closeObject
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_destroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    createImageObject
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_createImageObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    loadObjectJpegData
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_loadObjectJpegData
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    insertObjectIntoPage
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_insertObjectIntoPage
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    removeObjectFromPage
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_removeObjectFromPage
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    setObjectMatrix
 * Signature: (JFFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_setObjectMatrix
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    getObjectMatrix
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_getObjectMatrix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    createTextObject
 * Signature: (JLjava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_createTextObject
  (JNIEnv *, jclass, jlong, jstring, jfloat);

/*
 * Class:     org_swdc_pdfium_internal_PDFPageObjectImpl
 * Method:    setTextObjectString
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_pdfium_internal_PDFPageObjectImpl_setTextObjectString
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
