/* DO NOT EDIT THIS FILE - it is machine generated */
#include "Platform.h"
/* Header for class org_swdc_pdfium_internal_PDFWriterImpl */

#ifndef _Included_org_swdc_pdfium_internal_PDFWriterImpl
#define _Included_org_swdc_pdfium_internal_PDFWriterImpl

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_pdfium_internal_PDFWriterImpl
 * Method:    writeDocument
 * Signature: (JLorg/swdc/pdfium/internal/PDFOutputStream;)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_pdfium_internal_PDFWriterImpl_writeDocument
  (JNIEnv *, jclass, jlong, jobject);


#ifdef __cplusplus
}
#endif
#endif
