/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_pdfium_internal_PDFPageImpl */

#ifndef _Included_org_swdc_pdfium_internal_PDFPageImpl
#define _Included_org_swdc_pdfium_internal_PDFPageImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_pdfium_internal_PDFBitmapImpl
 * Method:    createBitmap
 * Signature: (IIZ)J
 */
JNIEXPORT jlong JNICALL Java_org_swdc_pdfium_internal_PDFBitmapImpl_createBitmap
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     org_swdc_pdfium_internal_PDFBitmapImpl
 * Method:    fillRect
 * Signature: (JIIIIJ)V
 */
JNIEXPORT void JNICALL Java_org_swdc_pdfium_internal_PDFBitmapImpl_fillRect
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jlong);

/*
 * Class:     org_swdc_pdfium_internal_PDFBitmapImpl
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_pdfium_internal_PDFBitmapImpl_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_pdfium_internal_PDFBitmapImpl
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_pdfium_internal_PDFBitmapImpl_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_pdfium_internal_PDFBitmapImpl
 * Method:    getStride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_swdc_pdfium_internal_PDFBitmapImpl_getStride
  (JNIEnv *, jclass, jlong);
  
/*
 * Class:     org_swdc_pdfium_internal_PDFBitmapImpl
 * Method:    getBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_swdc_pdfium_internal_PDFBitmapImpl_getBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_swdc_pdfium_internal_PDFBitmapImpl
 * Method:    releaseBitmap
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_pdfium_internal_PDFBitmapImpl_releaseBitmap
  (JNIEnv *, jclass, jlong);
#ifdef __cplusplus
}
#endif
#endif
